### ISSUE TITLE
Can't parse shielding key: buffer.readUIntBE is not a function

### ISSUE THREAD

**Issue by clangenb** [integritee-network/incognitee-frontend#3]
Finally, we have support for the worker again in javascript introduced in https://github.com/integritee-network/incognitee-frontend/pull/2, however, there is an error that I couldn't fix yet:

![image](https://github.com/integritee-network/incognitee-frontend/assets/37865735/819cc689-238f-4ab1-a08d-bf2d9fca8f3f)

I tried playing around with polyfills in the hope to make it work, but no success so far. I am unsure if it is a polyfill issue anyhow, as we seem to have access to `Buffer` because we can correctly call `u8aToBuffer` [here](https://github.com/encointer/encointer-js/blob/1ae8bbef69c0163319f40e24a59e476c3978207f/packages/worker-api/src/parsers.ts#L28).

Another potential [error source](https://blog.kleeut.com/2020/06/solving-bufferreaduintbe-is-not.html) is passing a wrong type instead of a `Buffer`. However, reading the code, I can't see where we could fail here, and I don't know how to precisely verify that. The debugger shows that we have a `Uint8Array`, which I reckon it is correct, `Buffer` is a subclass of `Uint8Array`.

![image](https://github.com/integritee-network/incognitee-frontend/assets/37865735/5229413a-481b-43b2-9db8-5a6cd2be5069)

I am currently at a loss and have no creative idea in how to proceed.
